// Functional requirements catalogue — representative subset for traceability viewer.
// Drawn from blueprint Section 7.
import type { Bi } from "./governanceData";

export type Priority = "must" | "should" | "could" | "wont";
export type ReqStatus = "met" | "in-progress" | "planned" | "gap";

export type Requirement = {
  id: string;
  category: Bi;
  title: Bi;
  shall: Bi;
  standards: string[]; // mapping codes
  priority: Priority;
  status: ReqStatus;
  module: string; // owning module nav key
  acceptance: Bi;
};

// 70 representative requirements covering all domains.
export const REQUIREMENTS: Requirement[] = [
  // Engagement
  { id: "FR-ENG-001", category: { en: "Engagement", ar: "التفاعل" }, title: { en: "Unified inbox", ar: "صندوق وارد موحّد" }, shall: { en: "Provide a unified agent inbox aggregating email, web chat, phone, social, WhatsApp, SMS, portal, and in-app messages.", ar: "يوفر صندوق وارد موحّداً يجمع البريد، المحادثة، الهاتف، التواصل الاجتماعي، واتساب، الرسائل النصية، البوابة، والتطبيق." }, standards: ["DGA", "EFQM"], priority: "must", status: "met", module: "/inbox", acceptance: { en: "All channels visible with filters and channel icons.", ar: "تظهر جميع القنوات بأيقونات وعوامل تصفية." } },
  { id: "FR-ENG-002", category: { en: "Engagement", ar: "التفاعل" }, title: { en: "Channel continuity", ar: "استمرارية القناة" }, shall: { en: "Preserve full context when a customer switches channels using a single conversation ID.", ar: "يحافظ على السياق عند تبديل القنوات عبر معرف محادثة موحّد." }, standards: ["DGA"], priority: "must", status: "met", module: "/inbox", acceptance: { en: "Channel switch shows full prior context.", ar: "يظهر السياق الكامل عند تبديل القناة." } },
  { id: "FR-ENG-003", category: { en: "Engagement", ar: "التفاعل" }, title: { en: "Bilingual live chat", ar: "محادثة ثنائية اللغة" }, shall: { en: "Provide bilingual web and in-app live chat with file attachments.", ar: "يوفر محادثة فورية ثنائية اللغة مع إرفاق ملفات." }, standards: ["DGA", "WCAG"], priority: "must", status: "met", module: "/inbox", acceptance: { en: "Latency < 2s send/receive.", ar: "زمن الإرسال أقل من ثانيتين." } },
  { id: "FR-ENG-004", category: { en: "Engagement", ar: "التفاعل" }, title: { en: "Telephony screen-pop", ar: "نافذة المتصل" }, shall: { en: "Integrate with telephony for screen-pop, recording, transcription, and disposition.", ar: "يتكامل مع الهاتف لنوافذ المتصل والتسجيل والتفريغ والتوصيف." }, standards: ["DGA"], priority: "should", status: "in-progress", module: "/inbox", acceptance: { en: "Screen-pop within 2s on ANI match.", ar: "نافذة المتصل خلال ثانيتين." } },
  { id: "FR-ENG-006", category: { en: "Engagement", ar: "التفاعل" }, title: { en: "Social listening", ar: "متابعة التواصل الاجتماعي" }, shall: { en: "Ingest and respond to public social mentions across approved networks.", ar: "يستقبل ويستجيب لذكر المنصة على الشبكات المعتمدة." }, standards: ["DGA"], priority: "should", status: "met", module: "/inbox", acceptance: { en: "Mentions appear ≤ 5 min.", ar: "تظهر الإشارات خلال 5 دقائق." } },
  { id: "FR-ENG-007", category: { en: "Engagement", ar: "التفاعل" }, title: { en: "WhatsApp Business", ar: "واتساب للأعمال" }, shall: { en: "Support official WhatsApp Business API messaging.", ar: "يدعم رسائل واتساب الرسمية للأعمال." }, standards: ["DGA"], priority: "must", status: "met", module: "/inbox", acceptance: { en: "Bi-directional with templates.", ar: "اتجاهان مع القوالب." } },
  { id: "FR-ENG-008", category: { en: "Engagement", ar: "التفاعل" }, title: { en: "SMS gateway", ar: "بوابة الرسائل النصية" }, shall: { en: "Send/receive SMS (transactional and conversational).", ar: "يرسل ويستقبل الرسائل النصية." }, standards: ["DGA"], priority: "should", status: "met", module: "/inbox", acceptance: { en: "Bidirectional with opt-out.", ar: "اتجاهان مع خيار الانسحاب." } },

  // Customer Data & Identity
  { id: "FR-CDI-001", category: { en: "Customer Data", ar: "بيانات المستفيد" }, title: { en: "360° profile", ar: "ملف شامل" }, shall: { en: "Present a unified customer profile aggregating identity, contacts, consents, interactions, cases, surveys, and entitlements.", ar: "يعرض ملفاً موحّداً للمستفيد." }, standards: ["DGA", "EFQM"], priority: "must", status: "met", module: "/complaints", acceptance: { en: "Single 360° view per customer.", ar: "ملف شامل لكل عميل." } },
  { id: "FR-CDI-002", category: { en: "Customer Data", ar: "بيانات المستفيد" }, title: { en: "Identity resolution", ar: "حل الهوية" }, shall: { en: "Deterministically and probabilistically resolve identities with confidence scoring.", ar: "يطابق الهويات يقينياً واحتمالياً." }, standards: ["DGA", "PDPL"], priority: "must", status: "met", module: "/admin", acceptance: { en: "Confidence score per match.", ar: "درجة ثقة لكل تطابق." } },
  { id: "FR-CDI-005", category: { en: "Customer Data", ar: "بيانات المستفيد" }, title: { en: "Consent management", ar: "إدارة الموافقات" }, shall: { en: "Capture, version, and enforce granular consents per purpose.", ar: "يلتقط ويُصدِر ويُطبّق الموافقات بحسب الغرض." }, standards: ["PDPL"], priority: "must", status: "met", module: "/admin", acceptance: { en: "Versioned consent with timestamp.", ar: "موافقة مؤرخة ومُصدَرة." } },
  { id: "FR-CDI-007", category: { en: "Customer Data", ar: "بيانات المستفيد" }, title: { en: "Data-subject rights", ar: "حقوق صاحب البيانات" }, shall: { en: "Support PDPL DSAR — access, correction, erasure, portability.", ar: "يدعم حقوق صاحب البيانات بموجب نظام حماية البيانات." }, standards: ["PDPL"], priority: "must", status: "in-progress", module: "/admin", acceptance: { en: "DSAR fulfilled within statutory window.", ar: "تنفيذ الطلب خلال المدة النظامية." } },
  { id: "FR-CDI-008", category: { en: "Customer Data", ar: "بيانات المستفيد" }, title: { en: "National ID federation", ar: "اتحاد الهوية الوطنية" }, shall: { en: "Federate identity with national IdP via OIDC/SAML where authorized.", ar: "اتحاد الهوية الوطنية عبر OIDC/SAML." }, standards: ["DGA", "NCA"], priority: "must", status: "met", module: "/admin", acceptance: { en: "Nafath federation live.", ar: "اتحاد نفاذ مُفعّل." } },

  // AI
  { id: "FR-AI-001", category: { en: "AI", ar: "الذكاء الاصطناعي" }, title: { en: "Bilingual chatbot", ar: "روبوت محادثة ثنائي اللغة" }, shall: { en: "Provide an AI chatbot for EN/AR NLU/NLG with citations.", ar: "يوفر روبوت محادثة ثنائي اللغة مع مراجع." }, standards: ["DGA"], priority: "must", status: "in-progress", module: "/copilot", acceptance: { en: "Cited answers; HITL for low confidence.", ar: "إجابات بمراجع وتدخل بشري عند الشك." } },
  { id: "FR-AI-002", category: { en: "AI", ar: "الذكاء الاصطناعي" }, title: { en: "Agent copilot", ar: "مساعد الموظف" }, shall: { en: "Summarize context, suggest responses, retrieve knowledge, draft replies subject to human review.", ar: "يلخص السياق ويقترح ردوداً ويسحب المعرفة بمراجعة بشرية." }, standards: ["DGA"], priority: "must", status: "met", module: "/copilot", acceptance: { en: "Drafts marked AI-generated.", ar: "المسودات موسومة كذكاء اصطناعي." } },
  { id: "FR-AI-003", category: { en: "AI", ar: "الذكاء الاصطناعي" }, title: { en: "Intelligent routing", ar: "توجيه ذكي" }, shall: { en: "Route interactions by intent, skill, language, sentiment, priority, and SLA risk.", ar: "يوجه التفاعلات حسب النية والمهارة واللغة والمشاعر والأولوية." }, standards: ["DGA"], priority: "must", status: "met", module: "/inbox", acceptance: { en: "Routing rules editable.", ar: "قواعد التوجيه قابلة للتحرير." } },
  { id: "FR-AI-007", category: { en: "AI", ar: "الذكاء الاصطناعي" }, title: { en: "Generative drafting", ar: "صياغة توليدية" }, shall: { en: "Draft replies with mandatory human review when confidence < threshold.", ar: "صياغة ردود مع مراجعة بشرية إلزامية عند انخفاض الثقة." }, standards: ["DGA"], priority: "must", status: "met", module: "/copilot", acceptance: { en: "Threshold configurable per channel.", ar: "العتبة قابلة للضبط لكل قناة." } },
  { id: "FR-AI-008", category: { en: "AI", ar: "الذكاء الاصطناعي" }, title: { en: "Hallucination controls", ar: "ضوابط الهلوسة" }, shall: { en: "Ground generative responses to approved knowledge and refuse out-of-scope queries.", ar: "تثبيت الردود على المعرفة المعتمدة ورفض ما هو خارج النطاق." }, standards: ["DGA"], priority: "must", status: "met", module: "/copilot", acceptance: { en: "Refusal rate logged.", ar: "تسجيل نسبة الرفض." } },
  { id: "FR-AI-009", category: { en: "AI", ar: "الذكاء الاصطناعي" }, title: { en: "Prompt governance", ar: "حوكمة التعليمات" }, shall: { en: "Version, review, and audit all production prompts.", ar: "إصدار ومراجعة وتدقيق كل التعليمات الإنتاجية." }, standards: ["DGA"], priority: "must", status: "in-progress", module: "/copilot", acceptance: { en: "Prompt registry with approver.", ar: "سجل تعليمات مع جهة موافِقة." } },
  { id: "FR-AI-010", category: { en: "AI", ar: "الذكاء الاصطناعي" }, title: { en: "Human-in-the-loop", ar: "تدخل بشري إلزامي" }, shall: { en: "Require human approval for customer-facing AI outputs in defined risk categories.", ar: "يلزم موافقة بشرية لمخرجات الذكاء الاصطناعي للعملاء في الفئات الحرجة." }, standards: ["DGA"], priority: "must", status: "met", module: "/copilot", acceptance: { en: "HITL audit trail.", ar: "مسار تدقيق للتدخل البشري." } },
  { id: "FR-AI-011", category: { en: "AI", ar: "الذكاء الاصطناعي" }, title: { en: "Bias monitoring", ar: "مراقبة التحيز" }, shall: { en: "Monitor AI outputs for bias indicators with periodic audits.", ar: "مراقبة مخرجات الذكاء الاصطناعي للتحيز." }, standards: ["DGA"], priority: "should", status: "planned", module: "/copilot", acceptance: { en: "Quarterly bias audit.", ar: "تدقيق ربعي للتحيز." } },

  // Case/Complaint
  { id: "FR-CCM-001", category: { en: "Complaints", ar: "الشكاوى" }, title: { en: "Case lifecycle", ar: "دورة حياة الحالة" }, shall: { en: "Provide full case lifecycle: create, classify, assign, work, escalate, resolve, close, reopen.", ar: "دورة حياة كاملة للحالة." }, standards: ["ISO9001", "ISO10002"], priority: "must", status: "met", module: "/complaints", acceptance: { en: "All states with transitions.", ar: "كل الحالات مع التحولات." } },
  { id: "FR-CCM-002", category: { en: "Complaints", ar: "الشكاوى" }, title: { en: "ISO 10002 workflow", ar: "دورة شكاوى ISO 10002" }, shall: { en: "Implement complaint intake, acknowledgement, tracking, investigation, decision, closure aligned to ISO 10002.", ar: "تنفيذ دورة شكاوى وفق ISO 10002." }, standards: ["ISO10002"], priority: "must", status: "met", module: "/complaints", acceptance: { en: "All ISO 10002 phases evidenced.", ar: "كل مراحل ISO 10002 موثقة." } },
  { id: "FR-CCM-003", category: { en: "Complaints", ar: "الشكاوى" }, title: { en: "SLA management", ar: "إدارة اتفاقيات الخدمة" }, shall: { en: "Manage multi-tier SLAs with pause/resume, business calendars, breach alerts.", ar: "إدارة اتفاقيات متعددة المستويات مع تعليق واستئناف." }, standards: ["ISO9001"], priority: "must", status: "met", module: "/complaints", acceptance: { en: "Breach alerts triggered.", ar: "تنبيهات التجاوز فعّالة." } },
  { id: "FR-CCM-007", category: { en: "Complaints", ar: "الشكاوى" }, title: { en: "Immutable audit trail", ar: "سجل تدقيق ثابت" }, shall: { en: "Maintain immutable, time-stamped audit trail of all case actions.", ar: "سجل تدقيق ثابت ومؤرخ لكل الإجراءات." }, standards: ["ISO27001", "PDPL"], priority: "must", status: "met", module: "/audit", acceptance: { en: "Tamper-evident store.", ar: "تخزين مقاوم للتعديل." } },
  { id: "FR-CCM-008", category: { en: "Complaints", ar: "الشكاوى" }, title: { en: "Confidentiality scoping", ar: "نطاق السرية" }, shall: { en: "Enforce role-based confidentiality on complaint records with reason-for-access logging.", ar: "تطبيق سرية حسب الدور مع تسجيل سبب الوصول." }, standards: ["ISO10002", "PDPL"], priority: "must", status: "met", module: "/complaints", acceptance: { en: "Reason-for-access logged.", ar: "تسجيل سبب الوصول." } },
  { id: "FR-CCM-009", category: { en: "Complaints", ar: "الشكاوى" }, title: { en: "Closed-loop CAPA", ar: "حلقة مغلقة CAPA" }, shall: { en: "Link recurring complaints to corrective action plans with owners and due dates.", ar: "ربط الشكاوى المتكررة بخطط إجراءات تصحيحية." }, standards: ["ISO9001", "ISO10002"], priority: "should", status: "in-progress", module: "/complaints", acceptance: { en: "CAPA ID linked to case.", ar: "ربط معرف CAPA بالحالة." } },
  { id: "FR-CCM-011", category: { en: "Complaints", ar: "الشكاوى" }, title: { en: "Anonymous complaints", ar: "شكاوى مجهولة الهوية" }, shall: { en: "Accept anonymous complaints with reduced workflow respecting confidentiality.", ar: "قبول شكاوى مجهولة مع سرية." }, standards: ["ISO10002"], priority: "should", status: "met", module: "/complaints", acceptance: { en: "Anonymous flag set.", ar: "علامة المجهولية مفعّلة." } },

  // Self-service & KB
  { id: "FR-SSK-001", category: { en: "Self-Service", ar: "الخدمة الذاتية" }, title: { en: "Beneficiary portal", ar: "بوابة المستفيد" }, shall: { en: "Provide a bilingual self-service portal with personalized dashboard.", ar: "توفير بوابة خدمة ذاتية ثنائية اللغة." }, standards: ["DGA", "WCAG"], priority: "must", status: "met", module: "/portal", acceptance: { en: "Personalized dashboard renders.", ar: "لوحة شخصية تعمل." } },
  { id: "FR-SSK-002", category: { en: "Knowledge", ar: "المعرفة" }, title: { en: "Bilingual KB", ar: "قاعدة معرفة ثنائية" }, shall: { en: "Manage knowledge in EN and AR with parity workflow.", ar: "إدارة محتوى المعرفة بالعربية والإنجليزية." }, standards: ["DGA", "ISO9001"], priority: "must", status: "met", module: "/kb", acceptance: { en: "AR/EN parity ≥ 98%.", ar: "تكافؤ اللغتين ≥ 98٪." } },
  { id: "FR-SSK-003", category: { en: "Knowledge", ar: "المعرفة" }, title: { en: "Semantic search", ar: "بحث دلالي" }, shall: { en: "Provide semantic + keyword search across EN/AR with synonyms and dialectal terms.", ar: "بحث دلالي ومفتاحي بالعربية والإنجليزية." }, standards: ["DGA"], priority: "must", status: "met", module: "/kb", acceptance: { en: "Dialect terms matched.", ar: "مطابقة المصطلحات الدارجة." } },
  { id: "FR-SSK-007", category: { en: "Knowledge", ar: "المعرفة" }, title: { en: "KB lifecycle", ar: "دورة حياة المعرفة" }, shall: { en: "Enforce author → review → publish → review-cycle → retire.", ar: "تطبيق دورة الكتابة والمراجعة والنشر والتقاعد." }, standards: ["ISO9001"], priority: "should", status: "met", module: "/kb", acceptance: { en: "Review cycle enforced.", ar: "دورة المراجعة مُلزِمة." } },

  // VoC
  { id: "FR-VOC-001", category: { en: "Voice of Customer", ar: "صوت المستفيد" }, title: { en: "Post-interaction survey", ar: "استبيان بعد التفاعل" }, shall: { en: "Trigger bilingual surveys at defined moments (post-chat, post-call, post-case).", ar: "إطلاق استبيانات بعد التفاعلات." }, standards: ["EFQM", "ISO9001"], priority: "must", status: "met", module: "/voc", acceptance: { en: "Survey rate per channel.", ar: "نسبة الاستبيانات لكل قناة." } },
  { id: "FR-VOC-004", category: { en: "Voice of Customer", ar: "صوت المستفيد" }, title: { en: "Theme & sentiment", ar: "المواضيع والمشاعر" }, shall: { en: "Auto-tag verbatims by theme and sentiment in EN/AR.", ar: "وسم آلي للمواضيع والمشاعر بالعربية والإنجليزية." }, standards: ["EFQM"], priority: "should", status: "met", module: "/voc", acceptance: { en: "AR sentiment F1 ≥ 0.85.", ar: "دقة العربية ≥ 0.85." } },
  { id: "FR-VOC-005", category: { en: "Voice of Customer", ar: "صوت المستفيد" }, title: { en: "Closed-loop", ar: "حلقة مغلقة" }, shall: { en: "Create follow-up tasks for detractors within defined SLA.", ar: "مهام متابعة للمعترضين ضمن المهلة." }, standards: ["EFQM", "ISO10002"], priority: "must", status: "in-progress", module: "/voc", acceptance: { en: "Follow-up within 48h.", ar: "متابعة خلال 48 ساعة." } },

  // Analytics
  { id: "FR-ANL-001", category: { en: "Analytics", ar: "التحليلات" }, title: { en: "Operational dashboards", ar: "لوحات التشغيل" }, shall: { en: "Provide real-time operational dashboards.", ar: "لوحات تشغيلية لحظية." }, standards: ["DGA", "EFQM"], priority: "must", status: "met", module: "/dashboard", acceptance: { en: "Real-time refresh.", ar: "تحديث لحظي." } },
  { id: "FR-ANL-002", category: { en: "Analytics", ar: "التحليلات" }, title: { en: "Executive scorecard", ar: "لوحة قيادة تنفيذية" }, shall: { en: "Provide a configurable executive CX scorecard.", ar: "لوحة تنفيذية قابلة للتهيئة." }, standards: ["EFQM"], priority: "must", status: "met", module: "/dashboard", acceptance: { en: "Executive view live.", ar: "العرض التنفيذي مُفعّل." } },
  { id: "FR-ANL-005", category: { en: "Analytics", ar: "التحليلات" }, title: { en: "Journey analytics", ar: "تحليلات الرحلات" }, shall: { en: "Analyze end-to-end journeys with funnel, drop-off, and friction metrics.", ar: "تحليل الرحلات الكاملة والاحتكاكات." }, standards: ["EFQM"], priority: "should", status: "in-progress", module: "/journeys", acceptance: { en: "Funnel drop-off visible.", ar: "نقاط الانسحاب ظاهرة." } },

  // Workforce/Quality
  { id: "FR-WFQ-002", category: { en: "Quality", ar: "الجودة" }, title: { en: "QA scorecards", ar: "بطاقات تقييم الجودة" }, shall: { en: "Manage QA scorecards with calibration and disputes.", ar: "إدارة بطاقات تقييم مع المعايرة." }, standards: ["ISO9001"], priority: "must", status: "met", module: "/audit", acceptance: { en: "Scorecards exportable.", ar: "تصدير البطاقات متاح." } },
  { id: "FR-WFQ-003", category: { en: "Quality", ar: "الجودة" }, title: { en: "AI-assisted QA", ar: "مراقبة جودة بالذكاء الاصطناعي" }, shall: { en: "Auto-score interactions across 100% of eligible volume with sampling validation.", ar: "تقييم تلقائي مع تحقق بالعينة." }, standards: ["DGA"], priority: "should", status: "planned", module: "/audit", acceptance: { en: "Auto-score F1 ≥ 0.80.", ar: "دقة التقييم ≥ 0.80." } },

  // Security
  { id: "FR-SEC-001", category: { en: "Security", ar: "الأمن" }, title: { en: "RBAC + ABAC", ar: "صلاحيات قائمة على الدور والسمات" }, shall: { en: "Implement role- and attribute-based access controls with least privilege.", ar: "صلاحيات حسب الدور والسمات بأقل امتياز." }, standards: ["NCA", "ISO27001"], priority: "must", status: "met", module: "/admin", acceptance: { en: "RBAC + ABAC live.", ar: "الصلاحيات مفعلة." } },
  { id: "FR-SEC-002", category: { en: "Security", ar: "الأمن" }, title: { en: "SSO + MFA", ar: "دخول موحد ومصادقة ثنائية" }, shall: { en: "Support SSO (OIDC/SAML) and MFA for privileged roles.", ar: "دعم دخول موحد ومصادقة ثنائية." }, standards: ["NCA"], priority: "must", status: "met", module: "/admin", acceptance: { en: "MFA enforced for admins.", ar: "المصادقة الثنائية إلزامية للمسؤولين." } },
  { id: "FR-SEC-003", category: { en: "Security", ar: "الأمن" }, title: { en: "Encryption", ar: "التشفير" }, shall: { en: "Encrypt data in transit (TLS 1.2+) and at rest (AES-256).", ar: "تشفير البيانات نقلاً وتخزيناً." }, standards: ["NCA", "ISO27001"], priority: "must", status: "met", module: "/admin", acceptance: { en: "TLS 1.3 only on edges.", ar: "TLS 1.3 فقط." } },
  { id: "FR-SEC-004", category: { en: "Security", ar: "الأمن" }, title: { en: "Audit logging", ar: "تسجيل التدقيق" }, shall: { en: "Log all access and changes with tamper-evident storage.", ar: "تسجيل الوصول والتعديلات بتخزين مقاوم للتلاعب." }, standards: ["NCA", "ISO27001", "PDPL"], priority: "must", status: "met", module: "/audit", acceptance: { en: "7-year retention.", ar: "احتفاظ 7 سنوات." } },
  { id: "FR-SEC-005", category: { en: "Security", ar: "الأمن" }, title: { en: "Retention policies", ar: "سياسات الاحتفاظ" }, shall: { en: "Enforce configurable retention/archival policies per data class.", ar: "سياسات احتفاظ قابلة للضبط لكل فئة." }, standards: ["PDPL"], priority: "must", status: "met", module: "/admin", acceptance: { en: "Policies versioned.", ar: "سياسات مُصدَرة." } },
  { id: "FR-SEC-007", category: { en: "Security", ar: "الأمن" }, title: { en: "API security", ar: "أمن الواجهات" }, shall: { en: "Enforce OAuth 2.0/OIDC, mTLS, rate limit, WAF.", ar: "تطبيق OAuth2 وmTLS وحدود الطلب وجدار الحماية." }, standards: ["NCA"], priority: "must", status: "met", module: "/admin", acceptance: { en: "WAF blocks OWASP top 10.", ar: "WAF يحجب أهم 10 ثغرات." } },

  // Integrations
  { id: "FR-INT-001", category: { en: "Integration", ar: "التكامل" }, title: { en: "REST + GraphQL APIs", ar: "واجهات REST و GraphQL" }, shall: { en: "Expose REST and GraphQL APIs with OpenAPI specs.", ar: "واجهات REST وGraphQL موثقة OpenAPI." }, standards: ["DGA"], priority: "must", status: "met", module: "/admin", acceptance: { en: "OpenAPI published.", ar: "OpenAPI منشور." } },
  { id: "FR-INT-002", category: { en: "Integration", ar: "التكامل" }, title: { en: "Event streaming", ar: "تدفق الأحداث" }, shall: { en: "Publish/consume events via standards-based streaming.", ar: "نشر واستهلاك الأحداث بمعايير قياسية." }, standards: ["DGA"], priority: "should", status: "met", module: "/admin", acceptance: { en: "Kafka topics published.", ar: "مواضيع Kafka منشورة." } },

  // UX
  { id: "FR-UX-001", category: { en: "UX/Accessibility", ar: "تجربة المستخدم وإمكانية الوصول" }, title: { en: "WCAG 2.2 AA", ar: "إمكانية الوصول WCAG 2.2 AA" }, shall: { en: "Meet WCAG 2.2 Level AA across all surfaces.", ar: "تحقيق WCAG 2.2 AA في كل الواجهات." }, standards: ["WCAG"], priority: "must", status: "in-progress", module: "/admin", acceptance: { en: "No critical/serious violations.", ar: "لا انتهاكات حرجة أو جدية." } },
  { id: "FR-UX-002", category: { en: "UX/Accessibility", ar: "تجربة المستخدم وإمكانية الوصول" }, title: { en: "AR RTL parity", ar: "تكافؤ العربية واليمين لليسار" }, shall: { en: "Ensure complete RTL parity for the Arabic experience.", ar: "تكافؤ كامل في تجربة العربية." }, standards: ["DGA", "WCAG"], priority: "must", status: "met", module: "/admin", acceptance: { en: "All flows verified in AR.", ar: "كل التدفقات مراجعة بالعربية." } },
  { id: "FR-UX-003", category: { en: "UX/Accessibility", ar: "تجربة المستخدم وإمكانية الوصول" }, title: { en: "Usability target", ar: "هدف قابلية الاستخدام" }, shall: { en: "Achieve SUS ≥ 80 in EN and AR usability studies.", ar: "تحقيق SUS ≥ 80 في الدراستين." }, standards: ["DGA"], priority: "should", status: "in-progress", module: "/admin", acceptance: { en: "SUS reports archived.", ar: "أرشفة تقارير SUS." } },

  // Localization
  { id: "FR-LOC-001", category: { en: "Localization", ar: "التعريب" }, title: { en: "EN/AR parity ≥ 98%", ar: "تكافؤ العربية والإنجليزية ≥ 98٪" }, shall: { en: "Maintain ≥ 98% content parity between EN and AR.", ar: "الحفاظ على تكافؤ ≥ 98٪." }, standards: ["DGA"], priority: "must", status: "met", module: "/kb", acceptance: { en: "Parity audited monthly.", ar: "تدقيق شهري." } },
  { id: "FR-LOC-002", category: { en: "Localization", ar: "التعريب" }, title: { en: "Number/date format", ar: "تنسيقات الأرقام والتاريخ" }, shall: { en: "Respect locale conventions for numbers, dates, currency.", ar: "احترام تنسيقات المنطقة." }, standards: ["DGA"], priority: "should", status: "met", module: "/admin", acceptance: { en: "Hijri/Gregorian both supported.", ar: "دعم الهجري والميلادي." } },

  // Governance / Compliance
  { id: "FR-GOV-001", category: { en: "Governance", ar: "الحوكمة" }, title: { en: "Service ownership registry", ar: "سجل ملكية الخدمات" }, shall: { en: "Maintain a registry of services, owners, SLAs, content with versioning.", ar: "سجل مُصدَر للخدمات والملاك واتفاقيات الخدمة." }, standards: ["ISO9001"], priority: "must", status: "met", module: "/governance", acceptance: { en: "Versioned registry exportable.", ar: "سجل مُصدَر قابل للتصدير." } },
  { id: "FR-GOV-002", category: { en: "Governance", ar: "الحوكمة" }, title: { en: "Policy-as-configuration", ar: "السياسات كتهيئة" }, shall: { en: "Externalize policies (SLA, routing, retention) as configuration.", ar: "إخراج السياسات كتهيئة." }, standards: ["DGA"], priority: "should", status: "met", module: "/admin", acceptance: { en: "Policies versioned.", ar: "السياسات مُصدَرة." } },
  { id: "FR-GOV-003", category: { en: "Governance", ar: "الحوكمة" }, title: { en: "Management review workspace", ar: "مساحة المراجعة الإدارية" }, shall: { en: "Compile management review inputs/outputs for ISO 9001/10002.", ar: "إعداد مدخلات ومخرجات المراجعة الإدارية." }, standards: ["ISO9001", "ISO10002"], priority: "should", status: "planned", module: "/governance", acceptance: { en: "Quarterly pack auto-generated.", ar: "حزمة ربعية تلقائية." } },
  { id: "FR-GOV-004", category: { en: "Governance", ar: "الحوكمة" }, title: { en: "CAPA register", ar: "سجل الإجراءات التصحيحية" }, shall: { en: "Maintain CAPA register linked to complaints, surveys, audits.", ar: "سجل CAPA مرتبط بالشكاوى والاستبيانات والتدقيقات." }, standards: ["ISO9001", "ISO10002"], priority: "must", status: "in-progress", module: "/audit", acceptance: { en: "CAPA closed within SLA.", ar: "إغلاق CAPA ضمن المهلة." } },

  // NFRs as requirements
  { id: "NFR-001", category: { en: "Performance", ar: "الأداء" }, title: { en: "Page interactive p95", ar: "تفاعل الصفحة p95" }, shall: { en: "Page interactive ≤ 2s p95 on broadband; ≤ 4s p95 on 4G.", ar: "تفاعل الصفحة ≤ 2 ث على العريض." }, standards: ["DGA"], priority: "must", status: "met", module: "/admin", acceptance: { en: "p95 monitored.", ar: "مراقبة p95." } },
  { id: "NFR-006", category: { en: "Availability", ar: "التوفر" }, title: { en: "Production uptime", ar: "زمن التشغيل" }, shall: { en: "≥ 99.9% monthly (core), 99.5% non-core.", ar: "≥ 99.9٪ للأساسي." }, standards: ["DGA"], priority: "must", status: "met", module: "/admin", acceptance: { en: "Tracked monthly.", ar: "متابعة شهرية." } },
  { id: "NFR-009", category: { en: "DR", ar: "التعافي" }, title: { en: "RTO ≤ 2h for critical", ar: "RTO ≤ 2 ساعة للحرجة" }, shall: { en: "Recovery time objective ≤ 2 hours for critical systems.", ar: "زمن استعادة ≤ 2 ساعة للحرجة." }, standards: ["DGA", "NCA"], priority: "must", status: "met", module: "/admin", acceptance: { en: "Quarterly DR drill.", ar: "تمرين تعافي ربعي." } },
  { id: "NFR-017", category: { en: "Accessibility", ar: "إمكانية الوصول" }, title: { en: "WCAG 2.2 AA audited", ar: "تدقيق WCAG 2.2 AA" }, shall: { en: "Audited WCAG 2.2 AA compliance.", ar: "امتثال WCAG 2.2 AA مُدقق." }, standards: ["WCAG"], priority: "must", status: "in-progress", module: "/admin", acceptance: { en: "Audit report on file.", ar: "تقرير تدقيق محفوظ." } },
  { id: "NFR-018", category: { en: "Localization", ar: "التعريب" }, title: { en: "EN/AR parity audit", ar: "تدقيق تكافؤ اللغات" }, shall: { en: "EN/AR parity ≥ 98%.", ar: "تكافؤ ≥ 98٪." }, standards: ["DGA"], priority: "must", status: "met", module: "/kb", acceptance: { en: "Audit monthly.", ar: "تدقيق شهري." } },
  { id: "NFR-023", category: { en: "Privacy", ar: "الخصوصية" }, title: { en: "DPIA mandatory", ar: "تقييم الأثر إلزامي" }, shall: { en: "DPIA for new high-risk processing.", ar: "DPIA إلزامي للحالات الحرجة." }, standards: ["PDPL"], priority: "must", status: "met", module: "/governance", acceptance: { en: "DPIA gate pre-launch.", ar: "بوابة DPIA قبل الإطلاق." } },

  // Emerging Tech
  { id: "FR-ET-001", category: { en: "Emerging Tech", ar: "التقنيات الناشئة" }, title: { en: "ET lifecycle workspace", ar: "مساحة دورة التقنيات الناشئة" }, shall: { en: "Manage ET initiatives from research to monitoring with stage gates.", ar: "إدارة مبادرات التقنيات الناشئة." }, standards: ["DGA"], priority: "should", status: "planned", module: "/programme", acceptance: { en: "Stage gate review minutes.", ar: "محاضر مراجعة البوابات." } },
  { id: "FR-ET-002", category: { en: "Emerging Tech", ar: "التقنيات الناشئة" }, title: { en: "PoC sandbox", ar: "بيئة تجريبية" }, shall: { en: "Isolated sandbox environments for ET PoCs.", ar: "بيئات معزولة للتجارب." }, standards: ["DGA", "NCA"], priority: "should", status: "planned", module: "/programme", acceptance: { en: "Sandbox isolated network.", ar: "بيئة معزولة شبكياً." } },

  // Knowledge analytics
  { id: "FR-SSK-006", category: { en: "Knowledge", ar: "المعرفة" }, title: { en: "Knowledge analytics", ar: "تحليلات المعرفة" }, shall: { en: "Track article usage, search no-results, ratings, decay.", ar: "متابعة استخدام المقالات وعدم العثور والتقييم." }, standards: ["EFQM"], priority: "should", status: "met", module: "/kb", acceptance: { en: "No-result dashboard live.", ar: "لوحة لا توجد نتائج فعّالة." } },

  // VoC continued
  { id: "FR-VOC-006", category: { en: "Voice of Customer", ar: "صوت المستفيد" }, title: { en: "Unified VoC dashboard", ar: "لوحة VoC موحّدة" }, shall: { en: "Aggregate CSAT, CES, NPS, themes, perception signals.", ar: "تجميع CSAT و CES و NPS والمواضيع." }, standards: ["EFQM"], priority: "must", status: "met", module: "/voc", acceptance: { en: "Single VoC view.", ar: "عرض موحد." } },

  // Workforce gap
  { id: "FR-WFQ-001", category: { en: "Workforce", ar: "القوى العاملة" }, title: { en: "Workforce management", ar: "إدارة القوى العاملة" }, shall: { en: "Forecast volumes, generate schedules, track adherence.", ar: "التنبؤ بالأحجام وجدولة الالتزام." }, standards: ["EFQM"], priority: "should", status: "gap", module: "/admin", acceptance: { en: "Forecast accuracy ≥ 85%.", ar: "دقة التنبؤ ≥ 85٪." } },

  // Knowledge bilingual
  { id: "FR-CCM-010", category: { en: "Complaints", ar: "الشكاوى" }, title: { en: "External body referral", ar: "إحالة لجهة خارجية" }, shall: { en: "Support handoff to external regulators/ombudsman with evidence package.", ar: "إحالة الشكاوى مع حزمة أدلة." }, standards: ["ISO10002"], priority: "should", status: "planned", module: "/complaints", acceptance: { en: "Evidence package generated.", ar: "حزمة أدلة جاهزة." } },

  // Data residency
  { id: "SEC-014", category: { en: "Security", ar: "الأمن" }, title: { en: "Data residency KSA", ar: "إقامة البيانات في السعودية" }, shall: { en: "All data at rest within approved KSA/GCC zones; cross-border only via approved mechanisms.", ar: "كل البيانات داخل المنطقة السعودية المعتمدة." }, standards: ["PDPL"], priority: "must", status: "met", module: "/admin", acceptance: { en: "Residency attestation.", ar: "إقرار الإقامة." } },
  { id: "SEC-019", category: { en: "AI Governance", ar: "حوكمة الذكاء الاصطناعي" }, title: { en: "AI governance & kill switch", ar: "حوكمة الذكاء الاصطناعي وإيقاف فوري" }, shall: { en: "Model & prompt registry; HITL; bias audits; kill switch.", ar: "سجل النماذج والتعليمات وإيقاف فوري." }, standards: ["DGA"], priority: "must", status: "in-progress", module: "/copilot", acceptance: { en: "Kill switch tested.", ar: "اختبار آلية الإيقاف." } },
  { id: "SEC-021", category: { en: "Privacy", ar: "الخصوصية" }, title: { en: "DSAR workflows", ar: "تدفقات طلبات أصحاب البيانات" }, shall: { en: "Access/correction/erasure/portability workflows.", ar: "تدفقات الوصول والتصحيح والمحو والنقل." }, standards: ["PDPL"], priority: "must", status: "in-progress", module: "/admin", acceptance: { en: "DSAR SLA tracked.", ar: "متابعة مهلة الطلب." } },
];
